name: Deploy SQL Objects

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Scan Secrets
        uses: gitleaks/gitleaks-action@v2

      - name: SQL Lint
        run: sqlfluff lint database/

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Stored Procedure
        run: |
          sqlcmd \
          -S localhost,1433 \
          -U sa \
          -P "${{ secrets.SQL_PASSWORD }}" \
          -N disable \
          -C \
          -i database/storedprocedure/testsp.sql
